#!/usr/bin/env bash
# One-shot deploy: renders configs/landing-zone.yaml, then applies every layer
# in dependency order.
#
# Safe to re-run. Each layer is a normal `terraform apply`, so a second run is
# a no-op where nothing changed. If it dies half-way, fix the cause and run it
# again — it picks up from the first layer that still has work.
set -euo pipefail
cd "$(dirname "$0")/.."

LAYERS=(01-organization 02-logging 03-config-recorders 04-security 05-network 06-identity)
BOOT=layers/00-bootstrap
AUTO=""
[[ "${1:-}" == "--yes" ]] && AUTO="-auto-approve"

command -v terraform >/dev/null || { echo "terraform not installed"; exit 1; }
python3 -c "import yaml" 2>/dev/null || { echo "python3 pyyaml not installed (pip install pyyaml)"; exit 1; }

echo "Rendering configs/landing-zone.yaml..."
python3 scripts/render.py
echo

if [[ -z "$AUTO" ]]; then
  cat <<'WARN'
This creates real AWS accounts. Account creation CANNOT be undone through the
API — closing an account is a manual, rate-limited console action. Check the
emails in configs/landing-zone.yaml before continuing.

WARN
  read -rp "Type 'deploy' to continue: " ok
  [[ "$ok" == "deploy" ]] || { echo "aborted"; exit 1; }
fi

# ── 00-bootstrap: the chicken and egg ─────────────────────────────────────────
# This layer creates the bucket that stores everyone's state, including its own,
# so it must start on a local backend and migrate afterwards.
if grep -q 'backend "local"' $BOOT/backend.tf; then
  echo "==> 00-bootstrap (local backend, first run)"
  terraform -chdir=$BOOT init -input=false
  terraform -chdir=$BOOT apply -input=false $AUTO

  BUCKET=$(terraform -chdir=$BOOT output -raw state_bucket_name)
  TABLE=$(terraform -chdir=$BOOT output -raw dynamodb_table_name)
  REGION=$(python3 -c "import yaml;print(yaml.safe_load(open('configs/landing-zone.yaml'))['regions']['primary'])")

  echo "==> migrating 00-bootstrap state into s3://$BUCKET"
  cat > $BOOT/backend.tf <<EOF
terraform {
  # Migrated from a local backend by scripts/deploy.sh on first run.
  # Values live in backend.s3.tfbackend, which is gitignored.
  backend "s3" {}
}
EOF
  cat > $BOOT/backend.s3.tfbackend <<EOF
# Generated by scripts/deploy.sh — do not edit.
bucket         = "$BUCKET"
key            = "lz/00-bootstrap/terraform.tfstate"
region         = "$REGION"
dynamodb_table = "$TABLE"
encrypt        = true
EOF
  terraform -chdir=$BOOT init -input=false -migrate-state -force-copy \
    -backend-config=backend.s3.tfbackend
else
  echo "==> 00-bootstrap (already on s3)"
  terraform -chdir=$BOOT init -input=false -backend-config=backend.s3.tfbackend
  terraform -chdir=$BOOT apply -input=false $AUTO
fi

# ── everything else ───────────────────────────────────────────────────────────
for layer in "${LAYERS[@]}"; do
  echo
  echo "==> $layer"
  terraform -chdir="layers/$layer" init -input=false -reconfigure \
    -backend-config=backend.s3.tfbackend
  terraform -chdir="layers/$layer" apply -input=false $AUTO
done

cat <<'DONE'

Landing zone deployed.

Two things Terraform could not do for you:
  1. Confirm the SNS subscription — check the alert_email inbox. Until someone
     clicks the link the subscription is pending and no alert is delivered.
  2. Enable IAM Identity Center and activate IAM billing access in the console
     if you have not already. See docs/KNOWN-LIMITS.md §2.
DONE
