#!/usr/bin/env python3
"""Fan configs/landing-zone.yaml out into per-layer Terraform inputs.

Writes, for each layer that needs them:
    layers/<layer>/terraform.tfvars.json
    layers/<layer>/backend.s3.tfbackend

Both are gitignored. Re-run this any time the YAML changes; it is idempotent.

Only pyyaml is required — no yq, no jq. Terraform reads .tfvars.json natively,
so no HCL is generated and nothing has to be escaped.
"""

import json
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONFIG = ROOT / "configs" / "landing-zone.yaml"

# Layers with no inputs of their own are omitted; every layer still gets a
# backend file.
LAYERS = [
    "00-bootstrap",
    "01-organization",
    "02-logging",
    "03-config-recorders",
    "04-security",
    "05-network",
    "06-identity",
]


def die(msg):
    sys.exit(f"render: {msg}")


def load():
    if not CONFIG.exists():
        die(f"{CONFIG.relative_to(ROOT)} not found")
    cfg = yaml.safe_load(CONFIG.read_text())

    for key in ("org_name", "unique_id", "aws_profile", "regions", "accounts"):
        if not cfg.get(key):
            die(f"'{key}' is required in {CONFIG.name}")
    for key in ("primary", "secondary"):
        if not cfg["regions"].get(key):
            die(f"regions.{key} is required")

    known_ous = set(cfg.get("ou_names") or [])
    for name, acct in cfg["accounts"].items():
        ou = acct.get("ou")
        if ou not in known_ous:
            die(f"account '{name}' has ou '{ou}', which is not in ou_names")
    return cfg


def derived(cfg):
    """Names computed from org_name + unique_id, overridable in the YAML."""
    stem = f"{cfg['org_name']}-lz"
    uid = cfg["unique_id"]
    over = cfg.get("bucket_overrides") or {}
    return {
        "state_bucket": over.get("state", f"{stem}-terraform-state-{uid}"),
        "lock_table": over.get("locks", f"{stem}-terraform-locks-{uid}"),
        "cloudtrail": over.get("cloudtrail", f"{stem}-cloudtrail-logs-{uid}"),
        "config": over.get("config", f"{stem}-config-logs-{uid}"),
        "flow_logs": over.get("flow_logs", f"{stem}-flow-logs-{uid}"),
    }


def accounts_for_terraform(cfg):
    """account name -> {email, ou_name}, filling emails from email_pattern."""
    pattern = cfg.get("email_pattern")
    out = {}
    for name, acct in cfg["accounts"].items():
        email = acct.get("email")
        if not email:
            if not pattern:
                die(f"account '{name}' has no email and email_pattern is unset")
            email = pattern.format(account=name.lower())
        out[name] = {"email": email, "ou_name": acct["ou"]}
    return out


def tfvars(cfg):
    """The per-layer input maps. Every value here traces back to one YAML key."""
    d = derived(cfg)
    profile = cfg["aws_profile"]
    regions = {"primary": cfg["regions"]["primary"], "secondary": cfg["regions"]["secondary"]}
    primary = regions["primary"]

    # Layers 02-06 all read upstream state from the same bucket.
    state = {"state_bucket": d["state_bucket"], "state_bucket_region": primary}

    return {
        "00-bootstrap": {
            "aws_region": primary,
            "aws_profile": profile,
            "org_name": cfg["org_name"],
            "unique_id": cfg["unique_id"],
            "github_org": (cfg.get("github") or {}).get("org", "my-org"),
            "github_repo": (cfg.get("github") or {}).get("repo", "*"),
        },
        "01-organization": {
            "aws_region": primary,
            "terraform-profile": profile,
            "ou_names": cfg.get("ou_names") or [],
            "accounts": accounts_for_terraform(cfg),
            "allowed_regions": regions,
        },
        "02-logging": {
            "terraform-profile": profile,
            "cloudtrail_bucket_name": d["cloudtrail"],
            "config_bucket_name": d["config"],
            "flow_logs_bucket_name": d["flow_logs"],
            **state,
        },
        "03-config-recorders": {"terraform-profile": profile, **state},
        "04-security": {
            "aws_region": primary,
            "terraform-profile": profile,
            "alert_email": cfg.get("alert_email", ""),
            "allowed_regions": regions,
            **state,
        },
        "05-network": {"terraform-profile": profile, **state},
        "06-identity": {
            "terraform-profile": profile,
            "sso_users": cfg.get("sso_users") or {},
            **state,
        },
    }


BACKEND = """# Generated by scripts/render.py from configs/landing-zone.yaml — do not edit.
# Used as: terraform init -backend-config=backend.s3.tfbackend
bucket         = "{bucket}"
key            = "lz/{layer}/terraform.tfstate"
region         = "{region}"
dynamodb_table = "{table}"
encrypt        = true
"""


def main():
    cfg = load()
    d = derived(cfg)
    vals = tfvars(cfg)
    primary = cfg["regions"]["primary"]

    for layer in LAYERS:
        ldir = ROOT / "layers" / layer
        if not ldir.is_dir():
            die(f"layers/{layer} does not exist")

        (ldir / "terraform.tfvars.json").write_text(json.dumps(vals[layer], indent=2) + "\n")

        # 00-bootstrap starts on a local backend and creates the bucket the
        # others use, so it gets its backend file only after deploy migrates it.
        if layer != "00-bootstrap":
            (ldir / "backend.s3.tfbackend").write_text(
                BACKEND.format(bucket=d["state_bucket"], layer=layer,
                               region=primary, table=d["lock_table"])
            )
        print(f"  {layer}")

    print(f"\nstate bucket: {d['state_bucket']}\nlock table:   {d['lock_table']}")


if __name__ == "__main__":
    main()
